name: Fetch and Save LTA Incidents

on:
  schedule:
    - cron: "0 */6 * * *" # runs every 6 hours
  workflow_dispatch:      

jobs:
  update-incidents:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          LTA_KEY: orxOhzCKSY+kXRrlIyWWrQ==
          SUPABASE_URL: https://wesscwzrsuyiqdeccysm.supabase.co
          SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indlc3Njd3pyc3V5aXFkZWNjeXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NzEwOTMsImV4cCI6MjA3MzE0NzA5M30.5BRLFWRcKaQlNUpOPRwVjP51M3kXaDH4YadqwY5Qmx0
          SUPABASE_TABLE: lta-incidents
          EXPIRATION_HOURS: 6
        run: npm start
